sudo: required
services:
  - docker

before_install:
  - docker build -t karlxignis/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true karlxignis/react-test npm test

after_success:
  - docker build -t karlxignis/multi-client ./client
  - docker build -t karlxignis/multi-nginx ./nginx
  - docker build -t karlxignis/multi-server ./server
  - docker build -t karlxignis/multi-worker ./worker